### ISSUE TITLE
Error get_registers -71

### ISSUE THREAD

**Issue by Mirkic7** [wget/realtek-r8152-linux#11]
I have USB  with Realtek 8156b chipset 2.5Gbe card, running Manjaro with kernel 5.10.15-1-MANJARO
I got this error in dmesg output:
kernel: r8152 2-1.3:1.0 enp0s20u1u3: get_registers -71
(was repeating in log every few mins)
Also, 2.5Gbe interface was not working with this error. Working again after reboot.

**Comment by hcartiaux** [comment]
Have you tried the AUR package [r8152-dkms](https://aur.archlinux.org/packages/r8152-dkms/) ? Where does your r8152 module comes from, which version are you using ?

Note that nobody here is affiliated with realtek, we have just decided to make the (GPLv2) code available on github in order to package it easily. Otherwise, the sources are hidden behind a portal on realtek.com.
